#! /bin/bash

case $1 in
	version)
		cat $HOME/.gg/gg.list | grep 'NOTE:' | lolcat
		echo ""	
	;;

	list)
		case $2 in
			shell)
				tput reset clear
				printf "[+] GitGun(gg) - Available Shell Scripts\n" | lolcat
				echo -e "----------------------------------------\n" | lolcat
				printf "shell\n"
				printf "zsh\n"
			;;

			tools)
				tput reset clear

				printf "[+] GitGun(gg) - Available Network Tools\n" | lolcat
				echo -e "----------------------------------------\n" | lolcat
				cat $HOME/.gg/gg.list | grep '/network/' | grep -v all | awk -F'::' '{ print $1 }'

				printf "\n[+] GitGun(gg) - Available Web Tools\n" | lolcat
				echo -e "--------------------------------------\n" | lolcat
				cat $HOME/.gg/gg.list | grep '/web/' | grep -v all | awk -F'::' '{ print $1 }'

			;;
		esac
	;;

	install)
		case $2 in
			all)
				case $3 in
					network)
						tput reset clear
						printf "[+] Installating All Network Tools\n" | lolcat
						sleep 1
						curl -s $(cat $HOME/.gg/gg.list | grep -w "all_network::" | awk -F'::' '{ print $2 }') | bash
						printf "\n[+] Installation Successful - All Network Tools\n" | lolcat
						printf "[+] Please Logoff and Login back\n" | lolcat
					;;

					web)
						tput reset clear
						printf "[+] Installating All Web Tools\n" | lolcat
						sleep 1
						curl -s $(cat $HOME/.gg/gg.list | grep -w "all_web::" | awk -F'::' '{ print $2 }') | bash
						printf "\n[+] Installation Successful - All Web Tools\n" | lolcat
						printf "[+] Please Logoff and Login back\n" | lolcat
					;;

					*)
						printf "[+] Specify your candidate (network/web)...\n" | lolcat
						exit 1
					;;
				esac
			;;

			*)
				if grep -wq "$2::" $HOME/.gg/gg.list;
				then
					curl -s $(cat $HOME/.gg/gg.list | grep -w "$2::" | awk -F'::' '{ print $2 }') | bash
				else
					printf "[+] Installation Candidate - Not Found...\n" | lolcat
					printf "[+] Install tools from 'gg list' using 'gg install <TOOL_NAME>'...\n" | lolcat
					printf "[+] You can also use 'gg install all network' or 'gg install all web'...\n" | lolcat
					exit 1
				fi
			;;
		esac
	;;

	update)
		tput reset clear
		case $2 in
			gg)
				printf "[+] Updating GitGun(gg)...\n" | lolcat
				wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/gg.list -O $HOME/.gg/gg.list
				printf "[+] GitGun(gg) has been updated...\n" | lolcat
				printf "[+] Type 'gg' or 'gg help' to get going...\n" | lolcat
				printf "[+] Type 'gg version' to get the version date...\n\n" | lolcat

				cat $HOME/.gg/gg.list | grep 'NOTE:' | lolcat
				echo ""
			;;

			tools)
				printf "[+] Updating Installed GitGun(gg) Tools\n" | lolcat
				echo -e "-----------------------------------\n" | lolcat

				printf "[+] Updating Installed Network Tools\n" | lolcat
				if [ -s $HOME/.gg/update-cache/gg_network.list ];
				then
					cat $HOME/.gg/update-cache/gg_network.list | \
					xargs -I{} bash -c 'printf "[+] Updating {}\n" | lolcat; \
					curl -s $(cat $HOME/.gg/gg.list | grep -w "{}::" | awk -F"::" "{ print $2 }") | bash; printf "\n"'
				fi

				printf "[+] Updating Installed Web Tools\n" | lolcat
				if [ -s $HOME/.gg/update-cache/gg_web.list ];
				then
					cat $HOME/.gg/update-cache/gg_web.list | \
					xargs -I{} bash -c 'printf "[+] Updating {}\n" | lolcat; \
					curl -s $(cat $HOME/.gg/gg.list | grep -w "{}::" | awk -F"::" "{ print $2 }") | bash; printf "\n"'
				fi

				printf "\n[+] Updated All GitGun(gg) Installed Tools \n" | lolcat
			;;

			shell)
				printf "[+] Updating GitGun(gg) Shell Profile\n" | lolcat
				echo -e "---------------------------------\n" | lolcat

				wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/bash_profile -O $HOME/.bash_profile
				wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/vimrc -O $HOME/.vimrc
				wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/tmux.conf -O $HOME/.tmux/tmux.conf
				wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/apt-update -O $HOME/.local/bin/apt-update
				chmod +x $HOME/.local/bin/apt-update
			    wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/clearRam -O $HOME/.local/bin/clearRam
			    chmod +x $HOME/.local/bin/clearRam

				printf "[+] Updated GitGun(gg) Shell Profile\n" | lolcat
			;;

			*)
				printf "[+] No Updating Candidate Found...\n" | lolcat
				printf "[+] Available Options - 'gg update gg/tools/shell'\n" | lolcat
				exit 1
			;;
		esac
	;;

	help|*)
		tput reset clear
        printf "WELCOME TO GITGUN(gg) - THE TOOLKIT MANAGER\n\
-------------------------------------------\n\
A toolkit manager to install most used penetration testing\n\
tools with least effort. It also includes custom shell scripts\n\
for '.bashrc' and '.zshrc'.\n\n\
Created By: Mr. Sup3rN0vaa\n\n\
[+] Syntax: gg <OPTIONS> <TOOL_NAME>\n\n\
[+] Options:\n\
------------\n\n\
[>] help - Offers this page\n\
---------------------------\n\
[>] version - Shows last release date of the local repository\n\
---------------------------------------------------------------------\n\
[>] list - Lists all available tools\n\
 [>] shell - Lists 'shell' commands available to install\n\
 [>] tools - Lists 'tools' commands available to install\n\
--------------------------------------------------------\n\
[>] install - Install the tools\n\
 [>] all - Install all the tools available\n\
  [>] network - Install all the network tools available\n\
  [>] web - Install all the web tools available\n\
 [>] You can 'install' tools individually as well from\n\
 [>] 'gg list tools' or 'gg list shell'\n\
-------------------------------------------------------\n\
[>] update - To update installed tools\n\
 [>] gg - Updates itself\n\
 [>] tools - Updates all the installed tools\n\
 [>] shell - Updates the local 'bash_profile' to the latest one\n\
---------------------------------------------------------------\n\n\
[+] Examples:\n\
 [>] 'gg list tools' - List all the tools available to install\n\
 [>] 'gg list shell' - List all the shell scripts available to install\n\
 [>] 'gg install shell' - Install My Custom Shell Scripts\n\
 [>] 'gg install zsh' - Install Oh-My-ZSH Theme on My Custom Shell\n\
 [>] 'gg install nmap' - Installs 'nmap' from 'gg list tools'\n\
 [>] 'gg install all network' - Installs all the network tools available in 'gg list tools'\n\
 [>] 'gg install all web' - Installs all the web tools available in 'gg list tools'\n\
 [>] 'gg update shell' - Updates my local bash_profile to recent one\n\
 [>] 'gg update tools' - Updates all the installed tools\n\n\
 To help, do reach out to me on 'Mr. Sup3rN0vaa <m2sup3rn0va@gmail.com>'
\n" | lolcat
	;;
esac