#! /bin/bash

case $1 in
	version)
		tput reset clear

		printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
		echo -e "------------------------------------\n" | lolcat
		cat $HOME/.gg/gg.list | grep 'NOTE:' | lolcat
		echo ""
	;;

	list)
		case $2 in
			help)
				tput reset clear

				printf "WELCOME TO GITGUN(gg) - THE TOOLKIT MANAGER\n\
-------------------------------------------\n\
A toolkit manager to install most used penetration testing\n\
tools with least effort. It also includes custom shell scripts\n\
for '.bashrc' and '.zshrc'.\n\n\
>>> Created By: Mr. Sup3rN0vaa <<<\n\
----------------------------------\n\n\
Syntax:\n\
-------\n\
gg list <OPTIONS>\n\n\
Options:\n\
--------\n\
help - Offers this page\n\
shell - Lists shell profile available to install\n\
tools - Lists all tools available to install\n\n\
Examples:\n\
---------\n\
'gg list tools' - List all the tools available to install\n\
'gg list shell' - List all the shell scripts available to install\n\n\
To help, do reach out to me on 'Mr. Sup3rN0vaa <m2sup3rn0va@gmail.com>'\n\n" | lolcat
			;;

			shell)
				tput reset clear

				printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
				echo -e "------------------------------------\n" | lolcat

				printf "[+] Available Shell Scripts\n" | lolcat
				echo -e "---------------------------\n" | lolcat
				printf "shell\n"
				printf "zsh\n"
				echo ""
			;;

			tools)
				tput reset clear

				printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
				echo -e "------------------------------------\n" | lolcat

				printf "[+] Available Network Tools\n" | lolcat
				echo -e "---------------------------\n" | lolcat
				cat $HOME/.gg/gg.list | grep '/network/' | grep -v all | awk -F'::' '{ print $1 }'

				printf "\n[+] Available Web Tools\n" | lolcat
				echo -e "-------------------------\n" | lolcat
				cat $HOME/.gg/gg.list | grep '/web/' | grep -v all | awk -F'::' '{ print $1 }'
				echo ""

				printf "\n[+] Available Misc Tools\n" | lolcat
				echo -e "-------------------------\n" | lolcat
				cat $HOME/.gg/gg.list | grep '/misc/' | grep -v all | awk -F'::' '{ print $1 }'
				echo ""

				#printf "\n[+] Available Cracking Tools\n" | lolcat
				#echo -e "-------------------------\n" | lolcat
				#cat $HOME/.gg/gg.list | grep '/cracking/' | grep -v all | awk -F'::' '{ print $1 }'
				#echo ""

				#printf "\n[+] Available Custom Scripts\n" | lolcat
				#echo -e "-------------------------\n" | lolcat
				#cat $HOME/.gg/gg.list | grep '/custom/' | grep -v all | awk -F'::' '{ print $1 }'
				#echo ""
			;;

			*)
				tput reset clear

				printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
				echo -e "------------------------------------\n" | lolcat
				printf "[+] Nothing to list\n" | lolcat
				printf "[+] Type: 'gg list help' for reference\n" | lolcat
				echo ""
		esac
	;;

	install)
		case $2 in
			help)
				tput reset clear

				printf "WELCOME TO GITGUN(gg) - THE TOOLKIT MANAGER\n\
-------------------------------------------\n\
A toolkit manager to install most used penetration testing\n\
tools with least effort. It also includes custom shell scripts\n\
for '.bashrc' and '.zshrc'.\n\n\
>>> Created By: Mr. Sup3rN0vaa <<<\n\
----------------------------------\n\n\
Syntax:\n\
-------\n\
gg install <OPTIONS>\n\n\
Options:\n\
--------\n\
help - Offers this page\n\
shell - Installs My Custom Shell Settings\n\
zsh - Install 'zsh' shell and applies 'Oh-My-ZSH' Themes\n\
tools - Installs all the tools in arsenal\n\n\
Examples:\n\
---------\n\
'gg install shell' - Installs My Custom Shell Settings\n\
'gg install zsh' - Install 'zsh' shell and applies 'Oh-My-ZSH' Themes\n\
'gg install nmap' - Install tools one-by-one. Get the tool-list from 'gg list tools'\n\
'gg install tools network/web/misc' - Install all the associated tools\n\n\
To help, do reach out to me on 'Mr. Sup3rN0vaa <m2sup3rn0va@gmail.com>'\n\n" | lolcat
			;;

			tools)
				case $3 in
					network)
						grep '/network/' $HOME/.gg/gg.list | awk -F'::' '{ print $2}' | \
						xargs -I{} bash -c 'curl -s {} | bash'

						tput reset clear
						printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
						echo -e "------------------------------------\n" | lolcat
						printf "[+] All Done\n" | lolcat
						printf "[+] Please Logoff and Login back\n\n" | lolcat
					;;

					web)
						grep '/web/' $HOME/.gg/gg.list | awk -F'::' '{ print $2}' | \
						xargs -I{} bash -c 'curl -s {} | bash'
						
						tput reset clear
						printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
						echo -e "------------------------------------\n" | lolcat
						printf "[+] All Done\n" | lolcat
						printf "[+] Please Logoff and Login back\n\n" | lolcat
					;;

					misc)
						grep '/misc/' $HOME/.gg/gg.list | awk -F'::' '{ print $2}' | \
						xargs -I{} bash -c 'curl -s {} | bash'
						
						tput reset clear
						printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
						echo -e "------------------------------------\n" | lolcat
						printf "[+] All Done\n" | lolcat
						printf "[+] Please Logoff and Login back\n\n" | lolcat
					;;

#					cracking)
#						grep '/cracking/' $HOME/.gg/gg.list | awk -F'::' '{ print $2}' | \
#						xargs -I{} bash -c 'curl -s {} | bash'
#
#						tput reset clear
#						printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
#						echo -e "------------------------------------\n" | lolcat
#						printf "[+] All Done\n" | lolcat
#						printf "[+] Please Logoff and Login back\n\n" | lolcat
#					;;

#					custom)
#						grep '/custom/' $HOME/.gg/gg.list | awk -F'::' '{ print $2}' | \
#						xargs -I{} bash -c 'curl -s {} | bash'
#
#						tput reset clear
#						printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
#						echo -e "------------------------------------\n" | lolcat
#						printf "[+] All Done\n" | lolcat
#						printf "[+] Please Logoff and Login back\n\n" | lolcat
#					;;

					*)
						tput reset clear

						printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
						echo -e "------------------------------------\n" | lolcat

						printf "[+] Nothing to install\n" | lolcat
						printf "[+] Type: 'gg install help' for reference\n" | lolcat
						echo ""
						exit 1
					;;
				esac
			;;

			*)
				if grep -wq "$2:" $HOME/.gg/gg.list;
				then
					curl -s $(sed -n "s/$2:://p" $HOME/.gg/gg.list) | bash
					echo ""
				else
					tput reset clear
					printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
					echo -e "------------------------------------\n" | lolcat
					printf "[+] Nothing to install\n" | lolcat
					printf "[+] Type: 'gg install help' for reference\n" | lolcat
					echo ""
					exit 1
				fi
			;;
		esac
	;;

	update)
		case $2 in
			help)
				tput reset clear

				printf "WELCOME TO GITGUN(gg) - THE TOOLKIT MANAGER\n\
-------------------------------------------\n\
A toolkit manager to install most used penetration testing\n\
tools with least effort. It also includes custom shell scripts\n\
for '.bashrc' and '.zshrc'.\n\n\
>>> Created By: Mr. Sup3rN0vaa <<<\n\
----------------------------------\n\n\
Syntax:\n\
-------\n\
gg update <OPTIONS>\n\n\
Options:\n\
--------\n\
help - Offers this page\n\
gg - Updates itself\n\
tools - Updates all the tools installed via GitGun\n\
shell - Updates the local shell profile\n\n\
Examples:\n\
---------\n\
'gg update tools network/web/misc' - Updates all the associated tools installed via GitGun(gg)\n\
'gg update gg' - Updates itself\n\
'gg update shell' - Updates the local shell profile\n\n\
To help, do reach out to me on 'Mr. Sup3rN0vaa <m2sup3rn0va@gmail.com>'\n\n" | lolcat
			;;

			gg)
				curl -s https://raw.githubusercontent.com/m2sup3rn0va/gg/main/install.sh | bash
			;;

			tools)
				case $3 in
					network)
						if [ -s $HOME/.gg/update-cache/gg_network.list ];
						then
							cat $HOME/.gg/update-cache/gg_network.list |\
							xargs -I{} bash -c 'curl -s $(sed -n "s/{}:://p" $HOME/.gg/gg.list) | bash;\
							printf "\n"'

							tput reset clear
							printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
							echo -e "------------------------------------\n" | lolcat
							printf "[+] All Done\n" | lolcat
							printf "[+] Please Logoff and Login back\n\n" | lolcat
						else
							tput reset clear
							printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
							echo -e "------------------------------------\n" | lolcat
							printf "[+] Network Tools - No Installation Candidate\n\n" | lolcat
						fi
					;;

					web)
						if [ -s $HOME/.gg/update-cache/gg_web.list ];
						then
							cat $HOME/.gg/update-cache/gg_web.list |\
							xargs -I{} bash -c 'curl -s $(sed -n "s/{}:://p" $HOME/.gg/gg.list) | bash;\
							printf "\n"'

							tput reset clear
							printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
							echo -e "------------------------------------\n" | lolcat
							printf "[+] All Done\n" | lolcat
							printf "[+] Please Logoff and Login back\n\n" | lolcat
						else
							tput reset clear
							printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
							echo -e "------------------------------------\n" | lolcat
							printf "[+] Web Tools - No Installation Candidate\n\n" | lolcat
						fi
					;;

					misc)
						if [ -s $HOME/.gg/update-cache/gg_misc.list ];
						then
							cat $HOME/.gg/update-cache/gg_misc.list |\
							xargs -I{} bash -c 'curl -s $(sed -n "s/{}:://p" $HOME/.gg/gg.list) | bash;\
							printf "\n"'

							tput reset clear
							printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
							echo -e "------------------------------------\n" | lolcat
							printf "[+] All Done\n" | lolcat
							printf "[+] Please Logoff and Login back\n\n" | lolcat
						else
							tput reset clear
							printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
							echo -e "------------------------------------\n" | lolcat
							printf "[+] Misc Tools - No Installation Candidate\n\n" | lolcat
						fi
					;;

					*)
						tput reset clear

						printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
						echo -e "------------------------------------\n" | lolcat
						printf "[+] Nothing to update\n" | lolcat
						printf "[+] Type: 'gg update help' for reference\n" | lolcat
						echo ""
						exit 1
					;;
				esac
			;;

			shell)
				tput reset clear
				printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
				echo -e "------------------------------------\n" | lolcat

				if [ -f $HOME/.bash_profile ];
				then
					printf "[+] Updating GitGun(gg) Shell Profile\n" | lolcat

					wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/bash_profile -O $HOME/.bash_profile
					wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/vimrc -O $HOME/.vimrc
					wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/tmux.conf -O $HOME/.tmux/tmux.conf
					wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/apt-update -O $HOME/.local/bin/apt-update
					chmod +x $HOME/.local/bin/apt-update
				    wget -q https://raw.githubusercontent.com/m2sup3rn0va/gg/main/ggs/shell/clearRam -O $HOME/.local/bin/clearRam
				    chmod +x $HOME/.local/bin/clearRam

				    printf "[+] Updated GitGun(gg) Shell Profile\n" | lolcat
				    printf "[+] Please Logoff and Login back\n\n" | lolcat
				else
					printf "[+] Nothing to update\n\n" | lolcat
				fi
			;;

			*)
				tput reset clear

				printf "[+] GITGUN(gg) - THE TOOLKIT MANAGER\n" | lolcat
				echo -e "------------------------------------\n" | lolcat
				printf "[+] Nothing to update\n" | lolcat
				printf "[+] Type: 'gg update help' for reference\n" | lolcat
				echo ""
				exit 1
			;;
		esac
	;;

	help|*)
		tput reset clear
        printf "WELCOME TO GITGUN(gg) - THE TOOLKIT MANAGER\n\
-------------------------------------------\n\
A toolkit manager to install most used penetration testing\n\
tools with least effort. It also includes custom shell scripts\n\
for '.bashrc' and '.zshrc'.\n\n\
>>> Created By: Mr. Sup3rN0vaa <<<\n\
----------------------------------\n\n\
Syntax:\n\
-------\n\
gg <OPTIONS> <TOOL_NAME>\n\n\
Options:\n\
--------\n\
help - Offers this page\n\
version - Shows last release date of the local repository\n\
list - Lists all available tools\n\
install - Install the tools\n\
update - To update installed tools\n\n\
Examples:\n\
---------\n\
'gg' or 'gg help' - Offers this page\n\
'gg version' - Lists current installed version\n\
'gg list help' - Help page of 'gg list'\n\
'gg install help' - Help page of 'gg install'\n\
'gg update help' - Help page of 'gg update'\n\n\
To help, do reach out to me on 'Mr. Sup3rN0vaa <m2sup3rn0va@gmail.com>'\n\n" | lolcat
	;;
esac